# Generated by Django 6.0.6 on 2026-06-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text='Article stays dark in light mode'),
        ),
    ]
