# Generated by Django 6.0.6 on 2026-06-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_link',
            field=models.URLField(blank=True, help_text='Enter Your social media link ', null=True),
        ),
    ]
