# Generated by Django 6.0.6 on 2026-06-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_user_last_name_change_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('author', 'Author'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
