# Generated by Django 6.0.6 on 2026-07-06 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakingNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Breaking news ka text (Max 200 characters)', max_length=200)),
                ('external_url', models.URLField(blank=True, help_text='Optional: Bahar ki kisi website ka link (e.g., BBC, Reuters)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Ticker mein dikhana hai ya nahi')),
                ('order', models.IntegerField(default=0, help_text='Priority (0 sabse upar)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, help_text='Optional: Kisi article se link karna ho toh select karo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breaking_news_items', to='news.article')),
            ],
            options={
                'verbose_name_plural': 'Breaking News',
                'ordering': ['-order', '-created_at'],
            },
        ),
    ]
