# Generated by Django 5.1.4 on 2026-07-10 11:00

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_breakingnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='breakingnews',
            name='article',
            field=models.ForeignKey(blank=True, help_text='Optional: If want to link any article Then Select Kisi ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breaking_news_items', to='news.article'),
        ),
        migrations.AlterField(
            model_name='breakingnews',
            name='external_url',
            field=models.URLField(blank=True, help_text='Optional: Outsider link  (e.g., BBC, Reuters)', null=True),
        ),
        migrations.AlterField(
            model_name='breakingnews',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Want to show in Ticker or not '),
        ),
        migrations.AlterField(
            model_name='breakingnews',
            name='order',
            field=models.IntegerField(default=0, help_text='Priority (0 top )'),
        ),
        migrations.AlterField(
            model_name='breakingnews',
            name='text',
            field=models.CharField(help_text='Breaking news text (Max 200 characters)', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
